name: ai-sales-development-representative
region: sgp

services:
  - name: app
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_size_slug: basic-xxs
    instance_count: 1
    routes:
      - path: /
    envs:
      - key: DATABASE_URL
        value: ""
        type: SECRET
      - key: SECRET_KEY
        value: ""
        type: SECRET
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: OPENAI_API_KEY
        value: ""
        type: SECRET
      - key: GEMINI_API_KEY
        value: ""
        type: SECRET
      - key: BACKEND_CORS_ORIGINS
        value: '["https://${APP_DOMAIN}","http://localhost:3000"]'
